### ISSUE TITLE
Allow different sizes for height and width 

### ISSUE THREAD

**Issue by AngrySoundTech** [CivMC/Civ#230]
Currently, we only support one `range:` for the size of a snitch.

Proposed config example after changes:

```yml
snitchConfigs:
  # A cube 
  snitch_1:
    range: 5

  # A rectangular cuboid
  snitch_2:
    range:
      height: 10
      width: 5
```

This has a "sister" issue of https://github.com/CivMC/Civ/issues/141
